class HandymanService {
  final String title;
  final String subtitle;
  final double minPrice;
  final double maxPrice;
  final String image;
  final String? badge;

  const HandymanService({
    required this.title,
    required this.subtitle,
    required this.minPrice,
    required this.maxPrice,
    required this.image,
    this.badge,
  });
}

const List<HandymanService> handymanServices = [
  HandymanService(
    title: "TV Mounting",
    subtitle: "Professional TV wall mounting",
    minPrice: 75,
    maxPrice: 150,
    image: "assets/images/tv_mounting.jpg",
    badge: "Popular",
  ),
  HandymanService(
    title: "Light Fixture Install",
    subtitle: "Replace or install new lights",
    minPrice: 60,
    maxPrice: 120,
    image: "assets/images/handyman_light.jpg",
    badge: "Popular",
  ),
  HandymanService(
    title: "Ceiling Fan Install",
    subtitle: "Install or replace ceiling fans",
    minPrice: 80,
    maxPrice: 180,
    image: "assets/images/handyman_fan.jpg",
    badge: "Popular",
  ),
  HandymanService(
    title: "Faucet Repair",
    subtitle: "Fix leaking faucets",
    minPrice: 70,
    maxPrice: 130,
    image: "assets/images/handyman_faucet.jpg",
    badge: "Popular",
  ),
  HandymanService(
    title: "Drywall Repair",
    subtitle: "Repair damaged drywall",
    minPrice: 90,
    maxPrice: 200,
    image: "assets/images/handyman_drywall.jpg",
    badge: "Popular",
  ),
  HandymanService(
    title: "Window/Door Repair",
    subtitle: "Fix windows and doors",
    minPrice: 80,
    maxPrice: 180,
    image: "assets/images/window_repair.jpg",
  ),
  HandymanService(
    title: "Small Painting",
    subtitle: "Touch-up and small painting",
    minPrice: 60,
    maxPrice: 150,
    image: "assets/images/small_painting.jpg",
  ),
  HandymanService(
    title: "Baby Proofing",
    subtitle: "Childproof your home",
    minPrice: 80,
    maxPrice: 150,
    image: "assets/images/baby_proofing.jpg",
  ),
  HandymanService(
    title: "Shelf Mounting",
    subtitle: "Mount shelves securely",
    minPrice: 50,
    maxPrice: 100,
    image: "assets/images/shelf_mounting.jpg",
  ),
  HandymanService(
    title: "Furniture Disassembly",
    subtitle: "Take apart furniture for moving",
    minPrice: 60,
    maxPrice: 150,
    image: "assets/images/furniture_disassembly.jpg",
  ),
  HandymanService(
    title: "Outdoor Furniture",
    subtitle: "Assemble outdoor furniture",
    minPrice: 70,
    maxPrice: 150,
    image: "assets/images/outdoor_furniture.jpg",
  ),
  HandymanService(
    title: "Curtain Rod Install",
    subtitle: "Install curtain rods and blinds",
    minPrice: 50,
    maxPrice: 100,
    image: "assets/images/curtain_rod_install.jpg",
  ),
  HandymanService(
    title: "Wall Patch Repair",
    subtitle: "Repair wall damage",
    minPrice: 60,
    maxPrice: 120,
    image: "assets/images/wall_patch_repair.jpg",
  ),
  HandymanService(
    title: "Appliance Hookup",
    subtitle: "Connect appliance safely",
    minPrice: 70,
    maxPrice: 130,
    image: "assets/images/appliance_hookup.jpg",
  ),
  HandymanService(
    title: "Minor Plumbing",
    subtitle: "Small plumbing repairs",
    minPrice: 60,
    maxPrice: 150,
    image: "assets/images/minor_plumbing.jpg",
  ),
  HandymanService(
    title: "Cabinet Repair",
    subtitle: "Fix cabinet doors and hinges",
    minPrice: 60,
    maxPrice: 120,
    image: "assets/images/cabinet_repair.jpg",
  ),
  HandymanService(
    title: "Clean Bathroom Fan",
    subtitle: "Remove dust, clean fan vent & improve airflow",
    minPrice: 40,
    maxPrice: 90,
    image: "assets/images/clean_bathroom_fan.jpg",
    badge: "Popular",
  ),
  HandymanService(
    title: "Replace Air Filters",
    subtitle: "Air, water & refrigerator filters",
    minPrice: 40,
    maxPrice: 120,
    image: "assets/images/air_filter.jpg",
    badge: "Popular",
  ),
  HandymanService(
    title: "Window Blinds",
    subtitle: "Install window blinds",
    minPrice: 50,
    maxPrice: 100,
    image: "assets/images/window_blinds.jpg",
  ),
  HandymanService(
    title: "Tile Caulking",
    subtitle: "Recaulk tiles and tubs",
    minPrice: 50,
    maxPrice: 100,
    image: "assets/images/tile_caulking.jpg",
  ),
  HandymanService(
    title: "Door Handle Fix",
    subtitle: "Repair or replace door handles",
    minPrice: 50,
    maxPrice: 100,
    image: "assets/images/door_handle_fix.jpg",
  ),
  HandymanService(
    title: "General Handyman",
    subtitle: "Various home repair tasks",
    minPrice: 60,
    maxPrice: 150,
    image: "assets/images/general_handyman.jpg",
  ),
  HandymanService(
    title: "Furniture Assembly",
    subtitle: "Assemble any furniture",
    minPrice: 60,
    maxPrice: 150,
    image: "assets/images/furniture_assembly.jpg",
    badge: "Popular",
  ),
  HandymanService(
    title: "Bed and Frame Assembly",
    subtitle: "Assemble beds and frames",
    minPrice: 70,
    maxPrice: 150,
    image: "assets/images/bed_frame_assembly.jpg",
    badge: "Popular",
  ),
  HandymanService(
    title: "Table Assembly",
    subtitle: "Assemble dining and coffee tables",
    minPrice: 50,
    maxPrice: 120,
    image: "assets/images/table_assembly.jpg",
  ),
  HandymanService(
    title: "Desk Assembly",
    subtitle: "Assemble office desks",
    minPrice: 60,
    maxPrice: 130,
    image: "assets/images/desk_assembly.jpg",
  ),
  HandymanService(
    title: "Sofa Assembly",
    subtitle: "Assemble sectional sofas",
    minPrice: 80,
    maxPrice: 150,
    image: "assets/images/sofa_assembly.jpg",
  ),
  HandymanService(
    title: "Dresser Assembly",
    subtitle: "Assemble dressers and drawers",
    minPrice: 70,
    maxPrice: 140,
    image: "assets/images/dresser_assembly.jpg",
  ),
  HandymanService(
    title: "Wardrobe Assembly",
    subtitle: "Assemble wardrobes and closets",
    minPrice: 80,
    maxPrice: 180,
    image: "assets/images/wardrobe_assembly.jpg",
  ),
  HandymanService(
    title: "Outdoor Furniture",
    subtitle: "Assemble patio furniture",
    minPrice: 70,
    maxPrice: 140,
    image: "assets/images/outdoor_furniture_assembly.jpg",
  ),
  HandymanService(
    title: "Baby Crib Assembly",
    subtitle: "Safely assemble baby cribs",
    minPrice: 60,
    maxPrice: 120,
    image: "assets/images/baby_crib_assembly.jpg",
    badge: "Popular",
  ),
  HandymanService(
    title: "Furniture Disassembly",
    subtitle: "Take apart furniture",
    minPrice: 50,
    maxPrice: 120,
    image: "assets/images/furniture_disassembly.jpg",
  ),
];
